apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apache-deployment
  name: apache-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apache-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apache-deployment
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}

