apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-automate
  name: k8s-automate
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: k8s-automate
  type: NodePort
status:
  loadBalancer: {}
